# Generated by Django 2.2 on 2020-10-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madlibs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=500)),
                ('noun2', models.CharField(max_length=500)),
            ],
        ),
    ]
